### ISSUE TITLE
How to monitor Voltage in HASS?

### ISSUE THREAD

**Issue by ptr727** [jkeljo/greeneye-monitor#1]
Hi, I found my way here after I could not figure out or find any docs on how to add a voltage sensor in HASS for a GEM.
Looks like only pulse counters, temperature probes, and current sensors are supported as sensors.

Is it possible to add a voltage sensor in HASS?

**Comment by jkeljo** [comment]
You mean a sensor for whatever the PT input is reading? I didn’t think to do that, but it wouldn’t be hard; this library does already expose the voltage so it’s just a matter of coding up an entity for it in Home Assistant. Mind filing an issue over there and tagging me? I’ll probably be able to get to it relatively soon.

**Comment by ptr727** [comment]
My request at HASS was closed, they do not like feature requests in the issue system.
https://github.com/home-assistant/home-assistant/issues/27285

**Comment by jkeljo** [comment]
Here ya go: https://github.com/home-assistant/home-assistant/pull/28418
