### ISSUE TITLE
Refactor onto sdwilsh/siobrultech-protocols

### ISSUE THREAD

**Issue by sdwilsh** [jkeljo/greeneye-monitor#6]
I factored out the `stream` and `packet` code from this library into a new, sans-I/O library at https://github.com/sdwilsh/siobrultech-protocols.  If you'd like, I can submit a pull request to add a dependency on that library, and refactor the code based on the sans-I/O API.

**Comment by jkeljo** [comment]
Well hello there, stranger! ;) I would happily accept such a pull request.
